services:
  mysql:
    image: arm64v8/mysql:8.0
    container_name: bitrix_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  php:
    image: arm64v8/php:8.2.28-apache
    container_name: bitrix_php
    restart: unless-stopped
    ports:
      - "8443:80"
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: bitrix
      DB_USER: bitrix
      DB_PASSWORD: bitrix